/*You are given two strings, s and t which only consist of lowercase letters. t is generated by shuffling the letters in s as well as potentially adding an additional random character. Return the letter that was randomly added to t if it exists, otherwise, return ’ ‘. 
Note: You may assume that at most one additional character can be added to t. 

Ex: Given the following strings...
s = "foobar", t = "barfoot", return 't'
s = "ide", t = "idea", return 'a'
s = "coding", t "ingcod", return ''*/

#include<stdio.h>
#include<string.h>

char spotTheDifference(char*,char*);

int main(void){
    char s1[7]="foobar",t1[8]="barfoot";
    printf("\'%c\' ",spotTheDifference(s1,t1));
    char s2[4]="ide",t2[5]="idea";
    printf("\'%c\' ",spotTheDifference(s2,t2));
    char s3[7]="coding",t3[7]="ingcod";
    printf("\'%c\' ",spotTheDifference(s3,t3));
    return 0;
}

char spotTheDifference(char*s,char*t){
    if(strlen(s)==strlen(t))
        return '\0';
    char c=0;
    for(int i=0;i<strlen(s);i++)
        c^=s[i];
    for(int i=0;i<strlen(t);i++)
        c^=t[i];
    return c;
}