/*You are given two strings, s and t which only consist of lowercase letters. t is generated by shuffling the letters in s as well as potentially adding an additional random character. Return the letter that was randomly added to t if it exists, otherwise, return ’ ‘. 
Note: You may assume that at most one additional character can be added to t. 

Ex: Given the following strings...
s = "foobar", t = "barfoot", return 't'
s = "ide", t = "idea", return 'a'
s = "coding", t "ingcod", return ''*/

#include<algorithm>
#include<iostream>

char spotTheDifference(std::string,std::string);

int main(){
    std::string s="foobar",t="barfoot";
    std::cout<<'\''<<spotTheDifference(s,t)<<'\''<<' ';
    s="ide",t="idea";
    std::cout<<'\''<<spotTheDifference(s,t)<<'\''<<' ';
    s="coding",t="ingcod";
    std::cout<<'\''<<spotTheDifference(s,t)<<'\''<<' ';
    return 0;
}

char spotTheDifference(std::string s,std::string t){
    if(s.length()==t.length())
        return '\0';
    std::sort(s.begin(),s.end());
    std::sort(t.begin(),t.end());
    for(int i=0;i<s.length();i++)
        if(s[i]!=t[i])
            return t[i];
    return t[t.length()-1];
}