/*You are given two strings, s and t which only consist of lowercase letters. t is generated by shuffling the letters in s as well as potentially adding an additional random character. Return the letter that was randomly added to t if it exists, otherwise, return ’ ‘. 
Note: You may assume that at most one additional character can be added to t. 

Ex: Given the following strings...
s = "foobar", t = "barfoot", return 't'
s = "ide", t = "idea", return 'a'
s = "coding", t "ingcod", return ''*/

class SpotTheDifference {
    public static void main(String args[]){
        System.out.println(spotTheDifference("foobar","barfoot"));
        System.out.println(spotTheDifference("ide","idea"));
        System.out.println(spotTheDifference("coding","ingcod"));
    }
    public static char spotTheDifference(String s,String t) {
        char c=0;
        for(char cs:s.toCharArray())
            c^=cs;
        for(char ct:t.toCharArray())
            c^=ct;
        return c;
    }
}
